name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:    
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://siva-vault.vault.bd767f40-f5c9-49b7-8f9f-5b060e7238b7.aws.hashicorp.cloud:8200
          role: ceidemo-staging
          method: jwt
          namespace: admin
          jwtGithubAudience: ceidemo
          secrets: secret/data/ceidemo/staging/db password        