name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get token and use the CLI
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo $JWT > test.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./test.txt          
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://siva-vault.vault.bd767f40-f5c9-49b7-8f9f-5b060e7238b7.aws.hashicorp.cloud:8200
          role: ceidemo-staging
          method: jwt
          jwtGithubAudience: o6s
          secrets: secret/ceidemo/staging/db password
          